//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hali.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> MarketID { get; set; }
        public Nullable<int> Piece { get; set; }
        public string Image { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public string CargoCode { get; set; }
        public Nullable<int> CargoID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public Nullable<double> m2 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CustomerName { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual User User { get; set; }
        public virtual Market Market { get; set; }
    }
}
